server:
    address: 0.0.0.0
    port: 8443
spring:
    data:
      mongodb:
        database: celhumid
        host: localhost
        port: 27017
    datasource:
        password: Fuller70n$
        url: jdbc:mysql://localhost:3306/fullertonid?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
#        url: jdbc:mysql://192.168.0.108:3306/fullertonid?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
        username: root
#        username: fullertonid
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

